### ISSUE TITLE
When in "New Post" selecting a new tag/sub erases written post content

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#65] opened 2019-11-19 18:31 UTC

**Comment by samosaboy** [comment] 2019-11-20 02:22
This is actually quite an extensive solution, the problem is re-rendering caused by react-select and the form component having deps to the select options. Will have to find a solution.

**Comment by Novusphere** [comment] 2019-11-20 03:15
@samosaboy Consider as a "simple solution" disabling writing anything (title/content) until it's selected with a clear message telling them that they first need to select a tag... but this does need to be resolved at some point.

**Comment by samosaboy** [comment] 2019-11-29 02:31
Fixed in 5b41f3191f7d70be999f5719e8d6320ed39e00e6

**Closed by samosaboy** 2019-11-29 02:31 UTC
Labels: bug
