### ISSUE TITLE
Content of editing an OP does not change

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#70] opened 2019-11-19 18:49 UTC
The request made to the server `/discussions/post` is still using the **old content** of the post, not the edited content. I'm not sure if this issue applies to editing replies as well, but worth looking into. I believe we had this problem with replies at one point but fixed it?

**Comment by samosaboy** [comment] 2019-11-19 22:05
Maybe this is fixed in 9da757299cff896edd32235bf4d893da3ed433f0 as I was not able to reproduce the above, but did fix the OP not changing immediately.

**Comment by samosaboy** [comment] 2019-11-20 00:48
Fixed in f832903c69cd457a5bfab9505d94d43820cdaaa0

**Closed by samosaboy** 2019-11-20 00:48 UTC
Labels: bug, high priority
